name: Playwright tests
on:
  repository_dispatch:
    types: [run-tests]
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    #zip the report
    - name: Zip report
      run: zip -r playwright-report.zip playwright-report
    # send report using  dawidd6/action-send-mail@v3
    - name: Send report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Playwright report
        body: Playwright report
        from: ${{ secrets.MAIL_USERNAME }}
        to: ${{ secrets.MAIL_USERNAME }}
        attachments: playwright-report.zip
  # download artifacts from the previous job and unzip them
  # publish:
  #   needs: test
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: playwright-report
  #       path: playwright-report
  #   - name: List files
  #     run: ls -R
    # - uses: actions/checkout@v3
    # - name: Install unzip
    #   run: choco install unzip
    #   shell: powershell
    # - name: Unzip report
    #   run: unzip playwright-report.zip -d playwright-report
    # - name: Get artifact ID
    #   uses: actions/github-script@v4
    #   id: artifact
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       const artifact = await github.actions.listWorkflowRunArtifacts({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         run_id: context.runId,
    #       });
    #       return artifact.data.artifacts[0].id;