name: Repository Dispatch
on:
  repository_dispatch:
    types: [run-tests]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print dispatched event payload
      run: echo ${{ github.event.client_payload }}
    
  